---
- name: List directory contents
  hosts: all
  become: yes
  connection: local
  gather_facts: false
  tasks:
    - name: List contents of /home/assert and save to file
      shell: ls /home/assert > /tmp/dir_contents.txt

    - name: Copy directory contents file to controller
      fetch:
        src: /tmp/dir_contents.txt
        dest: "./dir_contents_{{ inventory_hostname }}.txt"
        flat: yes
